### PR TITLE
added support for providing the dom element in stead of just the id

### PR DESCRIPTION
**Pull request by mauron85**
Implementing https://github.com/lugolabs/circles/pull/16

### CODE REVIEW

**Comment by rtsinani** [comment]
I don't think the line 74 with `console.log` is needed. What do you think?

**Comment by mauron85** [comment]
I was thinking about throwing error, when id or el options is not provided. What is the point of having instance that is actually unusable? But throwing error would be breaking change so instead I've put just warning.

Anyway if you don't like, throw it away. I don't mind. :-)

**Comment by rtsinani** [comment]
I think the DOM element option doesn't add much to the script.

**Comment by andreasheim** [comment]
Quite unfortunate that this PR was closed. We had been waiting for it to get merged. 

Use cases: 
Let's say you put multiple circles in a table. It's rather cumbersome/inconvenient having to create a unique id for each. On the other hand, it's straightforward to pick the element directly and pass it in. 

Or you may just have multiple modules on a page, each with a circle in them. They're all self-contained. I could easily create a circle from an element contained within one. However currently I need to come up with a mechanism to create unique ids (since they have to be unique).

**Pull request closed without merging**
